<?php
/**
 * Rebuild Url Rewrite for magento 2
 * Copyright (C) 2017
 *
 * This file is part of DanielSousa/UrlRewrite.
 *
 * DanielSousa/UrlRewrite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace DanielSousa\UrlRewrite\Console\Command;

use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class Categories extends AbstractUrlRewriteCommand
{

    /**
     * Name of product input option
     */
    const INPUT_CATEGORY = 'category';

    /**
     * Force of force input option
     */
    const INPUT_FORCE = 'force';

    /**
     * Name of product input option
     */
    const INPUT_STORE = 'store';

    /**
     * @var \Magento\Catalog\Model\ResourceModel\Category\Collection
     */
    protected $_collection = null;

    /**
     * Collections to process
     */
    protected $_collections = [];

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $options = [
            new InputOption(
                self::INPUT_CATEGORY,
                'c',
                InputOption::VALUE_OPTIONAL,
                'Reindex a specific category'
            ),
            new InputOption(
                self::INPUT_STORE,
                's',
                InputOption::VALUE_OPTIONAL,
                'Reindex a specific store',
                \Magento\Store\Model\Store::DEFAULT_STORE_ID
            )
        ];
        $this->setName('urlrewrite:rebuild:category');
        $this->setDescription('Rebuild Category URL Rewrites');
        $this->setDefinition($options);
        parent::configure();
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output);

        try {

            $categoryIds = $input->getOption(self::INPUT_CATEGORY);
            $storeId = $input->getOption(self::INPUT_STORE);
            $this->prepareCollections($storeId, $categoryIds);

            if ($size = $this->getSizeToProcess()) {
                $this->progressBar->start($size);
                $this->rebuildUrls();
            }

            $this->progressBar->finish();
            $this->output->write('', true);
        } catch (\Exception $e) {
            $this->output->writeln($e->getMessage());
            return \Magento\Framework\Console\Cli::RETURN_FAILURE;
        }
        return \Magento\Framework\Console\Cli::RETURN_SUCCESS;
    }

    /**
     * Generate product url by product
     * @param $args
     */
    public function callbackGenerateCategoryUrl($args)
    {
        $categoryId = null;
        try {
            if (!isset($args['row']['entity_id'])) {
                $this->output->writeln('Id not found');
                return;
            }
            $categoryId = $args['row']['entity_id'];
            $this->progressBar->setMessage($categoryId);
            $this->progressBar->advance();


            $product = clone $args['category'];
            $product->load($categoryId);

            $storeId = $args['storeId'];
            if (is_null($storeId)) {
                $storeId = \Magento\Store\Model\Store::DEFAULT_STORE_ID;
            }
            $product->setStoreId($storeId);
            $this->removeCategoryUrls($categoryId, $storeId);
            $this->replaceUrls(
                $this->prepareUrls($product)
            );
        } catch (\Exception $e) {
            if (!is_null($categoryId)) {
                $this->output->writeln('ERROR ON CATEGORY ID -' . $categoryId);
            }
            $this->output->writeln($e->getMessage());
            return;
        }
    }

    /**
     *  Remove Category urls
     *
     * @param $categoryId
     * @param null $storeId
     * @return bool
     */
    protected function removeCategoryUrls($categoryId, $storeId = null)
    {
        if (!is_numeric($categoryId)) {
            return false;
        }
        $data = [
            UrlRewrite::ENTITY_ID => $categoryId,
            UrlRewrite::ENTITY_TYPE => \Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator::ENTITY_TYPE,
            UrlRewrite::IS_AUTOGENERATED => 1,
            UrlRewrite::REDIRECT_TYPE => 0,
            UrlRewrite::STORE_ID => $storeId
        ];

        try {
            $this->getUrlPersist()->deleteByData($data);
        } catch (\Exception $e) {
            $this->output->writeln($e->getMessage());
            return false;
        }
        return true;
    }

    /**
     *  Generate list of product urls
     *
     * @param $product
     * @return array
     */
    private function prepareUrls($product)
    {
        return $this->getCategoryUrlRewriteGenerator()->generate($product);
    }

    /**
     *  Get Category Url Generator
     *
     * @return \Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator
     */
    protected function getCategoryUrlRewriteGenerator()
    {
        return $this->getObjectManager()->create('\Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator');
    }

    /**
     * Prepare Collections to process
     *
     * @param $storeId
     * @param $categoryIds
     * @throws \Exception
     */
    protected function prepareCollections($storeId, $categoryIds)
    {
        if (\Magento\Store\Model\Store::DEFAULT_STORE_ID == $storeId) {
            $stores = $this->getStoreManager()->getStores();
        } else {
            $stores = [$this->getStoreManager()->getStore($storeId)];
        }
        if (empty($stores)) {
            throw new \Exception('Invalid store');
        }

        foreach ($stores as $store) {
            $this->_collection = null;
            $storeId = $store->getId();
            $this->getCategoryCollection();
            $this->addFilterCategoryIds($categoryIds);
            //TODO: filter categories by store
//            $this->addStoreFilter($storeId);

            $this->addCollections($this->_collection, $storeId);
        }
    }

    /**
     * Get product collection
     *
     * @return \Magento\Catalog\Model\ResourceModel\Category\Collection
     */
    protected function getCategoryCollection()
    {
        if (is_null($this->_collection)) {
            /** @var \Magento\Catalog\Model\ResourceModel\Category\Collection $collection */
            $this->_collection = $this->getObjectManager()->create('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory')->create();
        }
        return $this->_collection;
    }

    /**
     * Filter collection by product ID
     *
     * @param null $categoryIds
     */
    private function addFilterCategoryIds($categoryIds = null)
    {
        if (is_null($categoryIds) || is_null($this->_collection)) {
            return;
        }
        $this->_collection->addIdFilter(explode(',', $categoryIds));
    }

    /**
     * Filter Collection by Store
     *
     * @param null $storeId
     */
    private function addStoreFilter($storeId = null)
    {
        if (is_null($storeId) || is_null($this->_collection)) {
            return;
        }
//        $this->_collection
//            ->addStoreFilter($storeId)
//            ->setStoreId($storeId);
    }

    /**
     * Add collection to process
     *
     * @param \Magento\Catalog\Model\ResourceModel\Category\Collection $collection
     * @param $storeId
     */
    protected function addCollections(\Magento\Catalog\Model\ResourceModel\Category\Collection $collection, $storeId)
    {
        $this->_collections[$storeId] = $collection;
    }

    /**
     * Number of Items to process
     *
     * @return int
     */
    protected function getSizeToProcess()
    {
        $size = 0;
        foreach ($this->_collections as $collection) {
            $size += $collection->getSize();
        }
        return $size;
    }

    /**
     * Rebuild Urls
     */
    protected function rebuildUrls()
    {
        foreach ($this->_collections as $storeId => $collection) {
            $this->getIterator()->walk(
                $collection->getSelect(),
                [[$this, 'callbackGenerateCategoryUrl']],
                [
                    'category' => $this->getCategoryFactory(),
                    'storeId' => $storeId
                ]
            );
        }

    }

    /**
     * Create product factory
     *
     * @return \Magento\Catalog\Model\CategoryFactory
     */
    protected function getCategoryFactory()
    {
        return $this->getObjectManager()->create('\Magento\Catalog\Model\CategoryFactory')->create();
    }
}